name: atomic
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - from-file: common/common-files.yml
  - from-file: common/river-modules.yml
  - from-file: common/sddm-modules.yml
