name: atomic
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - from-file: modules/common-files.yml
  - from-file: modules/river-modules.yml
  - from-file: modules/sddm-modules.yml
