name: atomic
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - from-file: common-files.yml
  - from-file: river-modules.yml
  - from-file: sddm-modules.yml
